# Generated by Django 4.1.13 on 2025-01-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_buah_jambu_mete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=1)),
                ('komentar', models.TextField(max_length=500)),
                ('ditambahkan', models.DateTimeField(auto_now_add=True)),
                ('diupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
