# Generated by Django 4.1.13 on 2025-01-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_buah_jambu_mete', '0002_komentar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komentar',
            old_name='komentar',
            new_name='komen',
        ),
        migrations.AlterField(
            model_name='komentar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
