# Generated by Django 4.1.13 on 2025-01-18 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_buah_jambu_mete', '0003_rename_komentar_komentar_komen_alter_komentar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='pengguna',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
